# Site settings
title: Homepage

# Author
author:
  name: Changqi Wang（王昶棋）
  desc: Hello and nice to meet you
  email: wangchangqi98@gmail.com
  selfie: assets/img/profile.png

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: WangChangqi98
  google_scholar: citations?user=uwIyOQ8AAAAJ
  instagram:
  keybase:
  linkedin:  
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: 
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
